---
- name: Persistent volume claim
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: '{{ claim_name }}'
        namespace: '{{ namespace }}'
        labels:
          app.kubernetes.io/name: '{{ app_name }}'
          app.kubernetes.io/instance: '{{ app_instance }}'
          app.kubernetes.io/managed-by: '{{ app_managed_by }}'
      spec:
        resources:
          requests:
            storage: '{{ storage }}'
        accessModes:
        - ReadWriteOnce
        storageClassName: '{{ storage_class_name }}'
