---
- name: Persistent volume claim
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: '{{ claim_name }}'
        namespace: '{{ namespace }}'
      spec:
        resources:
          requests:
            storage: '{{ storage }}'
        accessModes:
        - ReadWriteOnce
        storageClassName: '{{ storage_class_name }}'
