---
- name: Backend deployment
  community.kubernetes.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: '{{ backend_name }}'
        namespace: '{{ namespace }}'
        labels:
          app.kubernetes.io/name: '{{ app_name }}'
          app.kubernetes.io/instance: '{{ app_instance }}'
          app.kubernetes.io/managed-by: '{{ app_managed_by }}'
      spec:
        replicas: 1
        selector:
          matchLabels:
            name: '{{ backend_name }}'
        template:
          metadata:
            name: '{{ backend_name }}'
            labels:
              app.kubernetes.io/name: '{{ app_name }}'
              app.kubernetes.io/instance: '{{ app_instance }}'
              app.kubernetes.io/managed-by: '{{ app_managed_by }}'
              name: '{{ backend_name }}'
              networking/allow-internet-access: 'true'
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: kubernetes.io/arch
                      operator: In
                      values:
                      - amd64
            hostIPC: false
            hostNetwork: false
            hostPID: false
            securityContext:
              runAsNonRoot: false
            containers:
            - name: clearblade
              image: '{{ images.backend }}'
              securityContext:
                allowPrivilegeScalation: false
                capabilities:
                  drop:
                  - ALL
                privileged: false
                readOnlyRootFilesystem: false
                runAsNonRoot: false
              resources:
                limits:
                  memory: 512Mi
                requests:
                  cpu: 0.250
                  memory: 128Mi
              envFrom:
              - secretRef:
                  name: '{{ secret }}'
              command:
              - 'clearblade'
              args:
              - '-db'
              - 'postgres'
              - '-db-host'
              - '{{ database_name }}'
              - '-db-port'
              - '5432'
              - '-db-user'
              - 'clearblade'
              - '-db-pass'
              - 'password'
              - '-pkey'
              - '$(pkey)'
              ports:
              - name: mqtt
                containerPort: 1883
                protocol: TCP
              - name: ws
                containerPort: 8903
                protocol: TCP
              - name: http
                containerPort: 9000
                protocol: TCP
              readinessProbe:
                httpGet:
                  path: /api/about
                  port: 9000
              livenessProbe:
                httpGet:
                  path: /api/about
                  port: 9000

- name: Backend service
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ backend_name }}'
        namespace: '{{ namespace }}'
        labels:
          app.kubernetes.io/name: '{{ app_name }}'
          app.kubernetes.io/instance: '{{ app_instance }}'
          app.kubernetes.io/managed-by: '{{ app_managed_by }}'
      spec:
        ports:
        - name: http
          port: 80
          targetPort: http
        - name: mqtt
          port: 1883
          targetPort: mqtt
        - name: ws
          port: 8903
          targetPort: ws
        selector:
          name: '{{ backend_name }}'
