---
- name: Service account
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: '{{ service_account }}'
        namespace: '{{ namespace }}'
