# permissions for end users to edit clearblades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clearblade-editor-role
rules:
- apiGroups:
  - platform.clearblade.com
  resources:
  - clearblades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.clearblade.com
  resources:
  - clearblades/status
  verbs:
  - get
