# permissions for end users to view clearblades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clearblade-viewer-role
rules:
- apiGroups:
  - platform.clearblade.com
  resources:
  - clearblades
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - platform.clearblade.com
  resources:
  - clearblades/status
  verbs:
  - get
