---
- name: Console deployment
  community.kubernetes.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: '{{ console_name }}'
        namespace: '{{ namespace }}'
        labels:
          app.kubernetes.io/name: '{{ app_name }}'
          app.kubernetes.io/instance: '{{ app_instance }}'
          app.kubernetes.io/managed-by: '{{ app_managed_by }}'
      spec:
        replicas: 1
        selector:
          matchLabels:
            name: '{{ console_name }}'
        template:
          metadata:
            name: '{{ console_name }}'
            labels:
              app.kubernetes.io/name: '{{ app_name }}'
              app.kubernetes.io/instance: '{{ app_instance }}'
              app.kubernetes.io/managed-by: '{{ app_managed_by }}'
              name: '{{ console_name }}'
              networking/allow-internet-access: 'true'
          spec:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: kubernetes.io/arch
                      operator: In
                      values:
                      - amd64
            hostIPC: false
            hostNetwork: false
            hostPID: false
            securityContext:
              runAsNonRoot: false
            containers:
            - name: '{{ console_name }}'
              image: '{{ images.console }}'
              securityContext:
                allowPrivilegeScalation: false
                capabilities:
                  drop:
                  - ALL
                privileged: false
                readOnlyRootFilesystem: false
                runAsNonRoot: false
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 0.125
                  memory: 64Mi
              command:
              - 'cb_console'
              args:
              - '-platformURL'
              - '{{ http_proto }}://{{ domain }}'
              - '-platformPort'
              - '{{ http_port }}'
              - '-messageURL'
              - '{{ domain }}'
              - '-messagePort'
              - '8903'
              ports:
              - name: http
                containerPort: 3000
                protocol: TCP
              readinessProbe:
                httpGet:
                  path: /console-api/platformURL
                  port: 3000
              livenessProbe:
                httpGet:
                  path: /console-api/platformURL
                  port: 3000

- name: Console service
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ console_name }}'
        namespace: '{{ namespace }}'
        labels:
          app.kubernetes.io/name: '{{ app_name }}'
          app.kubernetes.io/instance: '{{ app_instance }}'
          app.kubernetes.io/managed-by: '{{ app_managed_by }}'
      spec:
        ports:
        - name: http
          port: 80
          targetPort: http
        selector:
          name: '{{ console_name }}'
