---
- hosts: localhost
  gather_facts: no
  collections:
    - community.kubernetes
    - operator_sdk.util
  roles:
    - prepare
    - service-account
    - network-policy
    - persistent
    - database
    - backend
    - console
    - haproxy
    - ingress
